"""Daily digest: render the ranked shortlist to markdown and (optionally) email it.

    python digest.py            build + write + email per config.delivery
    python digest.py --no-email just write the markdown file
    python digest.py --stdout   print to console, write nothing

Pulls from the current DB — run scrape.py first to refresh. Jobs at/above
delivery.min_score_for_digest are the shortlist; a few near-misses are appended
so the digest is useful even on a thin day.
"""
from __future__ import annotations

import argparse
import logging
import smtplib
import ssl
import sys
from datetime import date
from email.message import EmailMessage
from pathlib import Path

import config
import db

log = logging.getLogger("digest")


def _commute(j) -> str:
    if j.is_remote:
        return "remote"
    if j.commute_min:
        return f"~{j.commute_min} min ({j.nearest_station})"
    return j.location_normalized or "—"


def _salary(j) -> str:
    if j.salary_min and j.salary_max:
        return f"${j.salary_min//1000}k–${j.salary_max//1000}k"
    if j.salary_min:
        return f"${j.salary_min//1000}k+"
    return "salary n/a"


def _job_md(j, rank: int) -> str:
    new = " 🟢" if j.is_new else ""
    star = "★ " if j.score >= 0.8 else ""
    lines = [
        f"### {rank}. {star}{j.title} — {j.company or 'Unknown'}{new}",
        f"**{j.score:.2f}** · {j.role_type or '?'} · {_commute(j)} · {_salary(j)} · _{j.source}_",
    ]
    if j.qualification:
        yrs = f", ~{j.required_years}+ yrs" if j.required_years else ""
        q = f"**Qualification: {j.qualification}** (posting seniority: {j.seniority or '?'}{yrs})"
        if j.missing_requirements:
            q += f" — gaps: {'; '.join(j.missing_requirements[:3])}"
        lines.append(q)
    if j.fit_summary:
        lines.append(f"> {j.fit_summary}")
    lines.append(f"[View posting]({j.url})")
    return "\n\n".join(lines)


def build_markdown(primary: list, near: list, cfg: dict) -> str:
    thr = cfg["delivery"]["min_score_for_digest"]
    today = date.today().isoformat()
    out = [f"# Job Hunter — Daily Shortlist", f"_{today} · {len(primary)} match"
           f"{'es' if len(primary) != 1 else ''} (score ≥ {thr})_", ""]
    if primary:
        for i, j in enumerate(primary, 1):
            out.append(_job_md(j, i))
            out.append("\n---\n")
    else:
        out.append("_No postings cleared the bar today._\n")
    if near:
        out.append("## Near misses (below the bar)\n")
        for i, j in enumerate(near, 1):
            out.append(_job_md(j, i))
            out.append("\n---\n")
    out.append("\n_Generated by JobHunter._")
    return "\n".join(out)


def select(conn, cfg: dict) -> tuple[list, list]:
    d = cfg["delivery"]
    thr = d["min_score_for_digest"]
    cap = d.get("max_jobs_in_digest", 25)
    ranked = db.query(conn, order_by="score DESC")  # excludes dismissed
    primary = [j for j in ranked if j.score >= thr][:cap]
    near = [j for j in ranked if 0 < j.score < thr][:5] if len(primary) < 5 else []
    return primary, near


def write_file(md: str, cfg: dict) -> Path:
    d = cfg["delivery"]
    out_dir = Path(__file__).with_name(d.get("digest_dir", "digests"))
    out_dir.mkdir(exist_ok=True)
    path = out_dir / f"digest_{date.today().isoformat()}.md"
    path.write_text(md, encoding="utf-8")
    return path


def send_email(md: str, n: int, cfg: dict) -> bool:
    addr = config.env("GMAIL_ADDRESS")
    pw = config.env("GMAIL_APP_PASSWORD")
    if not addr or not pw:
        log.warning("Gmail not configured (.env) — skipping email.")
        return False
    pw = pw.replace(" ", "")  # app passwords are shown with spaces
    to = config.env("DIGEST_TO") or addr
    msg = EmailMessage()
    msg["Subject"] = f"JobHunter — {n} match{'es' if n != 1 else ''} ({date.today().isoformat()})"
    msg["From"] = addr
    msg["To"] = to
    msg.set_content(md)
    try:
        ctx = ssl.create_default_context()
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=ctx) as s:
            s.login(addr, pw)
            s.send_message(msg)
        log.info("emailed digest to %s", to)
        return True
    except Exception as e:  # noqa: BLE001
        log.error("email failed: %s", e)
        return False


def run(cfg: dict, *, write: bool = True, email: bool = True,
        to_stdout: bool = False) -> str:
    conn = db.connect()
    db.init_db(conn)
    primary, near = select(conn, cfg)
    md = build_markdown(primary, near, cfg)
    d = cfg["delivery"]
    if to_stdout:
        print(md)
        return md
    if write and d.get("write_markdown", True):
        path = write_file(md, cfg)
        log.info("wrote %s", path)
    if email and d.get("send_email", False):
        if send_email(md, len(primary), cfg):
            db.clear_new_flags(conn)  # only clear once successfully delivered
    conn.close()
    return md


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, ValueError):
        pass
    ap = argparse.ArgumentParser(description="Build/send the daily digest.")
    ap.add_argument("--no-email", action="store_true", help="write file but don't email")
    ap.add_argument("--stdout", action="store_true", help="print only, write nothing")
    args = ap.parse_args()
    cfg = config.load_config()
    run(cfg, email=not args.no_email, to_stdout=args.stdout)


if __name__ == "__main__":
    main()
