"""Daily digest: render the ranked shortlist to markdown and (optionally) email it.

    python digest.py            build + write + email per config.delivery
    python digest.py --no-email just write the markdown file
    python digest.py --stdout   print to console, write nothing

Pulls from the current DB — run scrape.py first to refresh. Jobs at/above
delivery.min_score_for_digest are the shortlist; a few near-misses are appended
so the digest is useful even on a thin day. If commute.google_maps.enabled is
on (config.yaml) and GOOGLE_MAPS_API_KEY is set (.env), shortlisted jobs get a
real transit-time refinement — see commute_precise.py.

Jobs already in an active application stage (applied/interviewing/offer, set via
mark.py) are excluded from the "apply now" suggestions and instead listed
compactly in an "Application pipeline" tracker at the bottom. Closed stages
(denied/withdrawn) drop out of the digest entirely.
"""
from __future__ import annotations

import argparse
import logging
import smtplib
import ssl
import sys
from dataclasses import replace
from datetime import date
from email.message import EmailMessage
from pathlib import Path

import commute
import commute_precise
import config
import db
import html_render
import logutil
import scorer

log = logging.getLogger("digest")


def _commute(j) -> str:
    if j.is_remote:
        return "remote"
    if j.commute_min_precise:
        return f"~{j.commute_min_precise} min real transit ({j.nearest_station})"
    if j.commute_min:
        return f"~{j.commute_min} min ({j.nearest_station})"
    return j.location_normalized or "—"


def _salary(j) -> str:
    if j.salary_min and j.salary_max:
        return f"${j.salary_min//1000}k–${j.salary_max//1000}k"
    if j.salary_min:
        return f"${j.salary_min//1000}k+"
    return "salary n/a"


def _job_md(j, rank: int, row_no: int | None) -> str:
    new = " 🟢" if j.is_new else ""
    star = "★ " if html_render.is_top_pick(j) else ""
    row = f"#{row_no}" if row_no is not None else "#?"
    lines = [
        f"### {rank}. {star}{j.title} — {j.company or 'Unknown'}{new}",
        f"**{j.score:.2f}** · {j.role_type or '?'} · {_commute(j)} · {_salary(j)} · _{j.source}_",
        f"`{j.id}` · {row}",
    ]
    if j.saved:
        lines[1] += " · ⭐ interested"
    if j.qualification:
        yrs = f", ~{j.required_years}+ yrs" if j.required_years else ""
        q = f"**Qualification: {j.qualification}** (posting seniority: {j.seniority or '?'}{yrs})"
        if j.missing_requirements:
            q += f" — top gap: {j.missing_requirements[0]}"
            extra = len(j.missing_requirements) - 1
            if extra:
                q += f" _(+{extra} more)_"
        lines.append(q)
    if j.fit_summary:
        # Lead with the verdict sentence only; full text is a `show.py <#>` away.
        lead, _ = html_render.lead_sentence(j.fit_summary)
        lines.append(f"> {lead}")
    lines.append(f"[View posting]({j.url})")
    return "\n\n".join(lines)


def _tracker_md(tracked: list, row_of: dict[str, int]) -> list[str]:
    if not tracked:
        return []
    out = [f"## Application pipeline ({len(tracked)})\n",
           "_Already in progress — kept out of the suggestions above._\n"]
    for _st, label, members in html_render.group_by_stage(tracked):
        for j in members:
            when = f" · since {j.stage_at.date().isoformat()}" if j.stage_at else ""
            row = f" · #{row_of[j.id]}" if row_of.get(j.id) is not None else ""
            out.append(f"- **{label}** · {j.title} — {j.company or 'Unknown'}{when} · "
                       f"[posting]({j.url}) · `{j.id}`{row}")
    return out


def build_markdown(primary: list, near: list, tracked: list, cfg: dict,
                   row_of: dict[str, int]) -> str:
    thr = cfg["delivery"]["min_score_for_digest"]
    today = date.today().isoformat()
    out = [f"# Job Hunter — Daily Shortlist", f"_{today} · {len(primary)} match"
           f"{'es' if len(primary) != 1 else ''} (score ≥ {thr})_", ""]
    if primary:
        for label, members in html_render.group_by_qual(primary):
            out.append(f"## {label} ({len(members)})\n")
            for i, j in enumerate(members, 1):
                out.append(_job_md(j, i, row_of.get(j.id)))
                out.append("\n---\n")
    else:
        out.append("_No postings cleared the bar today._\n")
    if near:
        out.append("## Near misses (below the bar)\n")
        for i, j in enumerate(near, 1):
            out.append(_job_md(j, i, row_of.get(j.id)))
            out.append("\n---\n")
    out += _tracker_md(tracked, row_of)
    out.append("\n_Generated by JobHunter._")
    return "\n".join(out)


def row_numbers(conn) -> dict[str, int]:
    """Map job id -> its row # in show.py's terminal list, so a digest entry
    can be looked up there directly. Must mirror show.py main()'s default
    query exactly (same inclusions, same order) since row numbers are only
    meaningful against that one canonical, full, unfiltered list."""
    full = db.query(conn, include_dismissed=True, include_duplicates=True,
                     order_by="score DESC")
    return {j.id: i for i, j in enumerate(full)}


def _correct_score(job, cfg: dict) -> float:
    """Recompute job's score using its cached precise commute time (see
    job.commute_min_precise) in place of the free bucket estimate. In-memory
    only — never written back to the DB; see commute_precise.py."""
    breakdown = dict(job.score_breakdown) if isinstance(job.score_breakdown, dict) else {}
    breakdown["commute"] = commute._bucket_score(
        job.commute_min_precise, cfg["commute"]["score_buckets"])
    total, _breakdown, _disq = scorer.score_job(replace(job, score_breakdown=breakdown), cfg)
    return total


def select(conn, cfg: dict, *, refine: bool = True) -> tuple[list, list, list]:
    d = cfg["delivery"]
    thr = d["min_score_for_digest"]
    cap = d.get("max_jobs_in_digest", 25)
    ranked = db.query(conn, order_by="score DESC")  # excludes dismissed/duplicates
    # Jobs already in an active pipeline stage go to the tracker, not the
    # suggestions. `open_jobs` are the ones with no stage set yet.
    open_jobs, tracked = html_render.split_by_stage(ranked)

    if refine:
        # Jobs whose free-estimate score is close enough to the cutoff that a
        # coarse commute bucket could plausibly be misjudging them — refine
        # and re-score those *before* the cut so a real transit time can move
        # them across the line either way. No-ops (and costs nothing) when
        # google_maps refinement isn't configured; see commute_precise.py.
        margin = cfg["commute"].get("google_maps", {}).get("correction_margin", 0.05)
        borderline = [j for j in open_jobs
                      if not j.is_remote and thr - margin <= j.score < thr + margin]
        commute_precise.refine_missing(conn, borderline, cfg)
        resorted = False
        for j in borderline:
            if j.commute_min_precise is not None:
                j.score = _correct_score(j, cfg)
                resorted = True
        if resorted:
            open_jobs.sort(key=lambda j: j.score, reverse=True)

    primary = [j for j in open_jobs if j.score >= thr][:cap]
    near = [j for j in open_jobs if 0 < j.score < thr][:5] if len(primary) < 5 else []
    if refine:
        # Real transit time (display only, doesn't affect ranking) for whatever
        # made the shortlist but wasn't already refined above as borderline.
        commute_precise.refine_missing(conn, primary + near, cfg)
    return primary, near, tracked


def write_file(md: str, cfg: dict) -> Path:
    d = cfg["delivery"]
    out_dir = Path(__file__).with_name(d.get("digest_dir", "digests"))
    out_dir.mkdir(exist_ok=True)
    path = out_dir / f"digest_{date.today().isoformat()}.md"
    path.write_text(md, encoding="utf-8")
    return path


def send_email(md: str, html_body: str, n: int, cfg: dict) -> bool:
    addr = config.env("GMAIL_ADDRESS")
    pw = config.env("GMAIL_APP_PASSWORD")
    if not addr or not pw:
        log.warning("Gmail not configured (.env) — skipping email.")
        return False
    pw = pw.replace(" ", "")  # app passwords are shown with spaces
    to = config.env("DIGEST_TO") or addr
    msg = EmailMessage()
    msg["Subject"] = f"JobHunter — {n} match{'es' if n != 1 else ''} ({date.today().isoformat()})"
    msg["From"] = addr
    msg["To"] = to
    msg.set_content(md)                       # plain-text fallback (markdown)
    msg.add_alternative(html_body, subtype="html")  # the version Gmail shows
    try:
        ctx = ssl.create_default_context()
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=ctx) as s:
            s.login(addr, pw)
            s.send_message(msg)
        log.info("emailed digest to %s", to)
        return True
    except Exception as e:  # noqa: BLE001
        log.error("email failed: %s", e)
        return False


def run(cfg: dict, *, write: bool = True, email: bool = True,
        to_stdout: bool = False) -> str:
    conn = db.connect()
    db.init_db(conn)
    primary, near, tracked = select(conn, cfg)
    row_of = row_numbers(conn)
    md = build_markdown(primary, near, tracked, cfg, row_of)
    d = cfg["delivery"]
    if to_stdout:
        print(md)
        return md
    if write and d.get("write_markdown", True):
        path = write_file(md, cfg)
        log.info("wrote %s", path)
    if email and d.get("send_email", False):
        html_body = html_render.digest_html(primary, near, tracked, cfg, row_of)
        if send_email(md, html_body, len(primary), cfg):
            db.clear_new_flags(conn)  # only clear once successfully delivered
    conn.close()
    return md


def main() -> None:
    logutil.setup_logging()
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except (AttributeError, ValueError):
        pass
    ap = argparse.ArgumentParser(description="Build/send the daily digest.")
    ap.add_argument("--no-email", action="store_true", help="write file but don't email")
    ap.add_argument("--stdout", action="store_true", help="print only, write nothing")
    args = ap.parse_args()
    cfg = config.load_config()
    run(cfg, email=not args.no_email, to_stdout=args.stdout)


if __name__ == "__main__":
    main()
